import { useEffect, useState } from 'react'; import { Link, useNavigate } from 'react-router-dom'; import { api } from '../../api'; import { useAuth } from '../../auth/AuthContext'; import styles from '../forms.module.css';
const periods = ['Temuriylar davri', 'Jadid davri', 'Sovet davri', 'Mustaqillik davri']; const genres = ['fantastik', 'badiiy', 'drama', 'melodrama', 'detektiv', 'sarguzasht', 'tarixiy', 'ilmiy-fantastik'];
export default function AddBook() {
  const { user, loading } = useAuth(); const navigate = useNavigate(); const [authors, setAuthors] = useState([]); const [form, setForm] = useState({ title:'', period:periods[0], published_year:'', pages:'', publisher:'', genres:genres[0], details:'', author_info:'' }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!loading && user?.role !== 'admin') navigate('/books'); }, [user, loading, navigate]); useEffect(() => { if (user?.role === 'admin') api('/get_all_authors').then(setAuthors).catch((err) => setError(err.message)); }, [user]);
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); setError(''); await api('/add_book', { method:'POST', body:JSON.stringify({ ...form, published_year:Number(form.published_year), pages:Number(form.pages) }) }); setSuccess('Kitob muvaffaqiyatli qo‘shildi.'); setTimeout(() => navigate('/books'), 900); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  if (loading || user?.role !== 'admin') return null; const field = (label, name, type = 'text') => <div className={styles.field}><label>{label}</label><input required type={type} name={name} value={form[name]} onChange={(event) => setForm({...form,[name]:event.target.value})}/></div>;
  return <section className={styles.page}><div className={styles.wrap}><h1 className={styles.title}>Kitob qo‘shish</h1><p className={styles.subtitle}>Kitob ma’lumotlarini kiriting va muallifni tanlang.</p><div className={styles.tabs}><Link className={styles.tab} to="/add-author">Adib qo‘shish</Link></div><form className={styles.form} onSubmit={submit}>{field('Kitob nomi','title')}{field('Nashriyot','publisher')}{field('Nashr yili','published_year','number')}{field('Sahifalar soni','pages','number')}<div className={styles.field}><label>Davr</label><select value={form.period} onChange={(event) => setForm({...form,period:event.target.value})}>{periods.map((period) => <option key={period}>{period}</option>)}</select></div><div className={styles.field}><label>Janr</label><select value={form.genres} onChange={(event) => setForm({...form,genres:event.target.value})}>{genres.map((genre) => <option key={genre}>{genre}</option>)}</select></div><div className={`${styles.field} ${styles.full}`}><label>Muallif</label><select required value={form.author_info} onChange={(event) => setForm({...form,author_info:event.target.value})}><option value="">Muallifni tanlang</option>{authors.map((author) => <option value={author._id} key={author._id}>{author.full_name}</option>)}</select></div><div className={`${styles.field} ${styles.full}`}><label>Tavsif</label><textarea required value={form.details} onChange={(event) => setForm({...form,details:event.target.value})} /></div>{error && <p className={styles.error}>{error}</p>}{success && <p className={styles.success}>{success}</p>}<button className={styles.button} disabled={saving}>{saving ? 'Saqlanmoqda...' : 'Kitobni qo‘shish'}</button></form></div></section>;
}
